Vagrant.configure("2") do |config|

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  
  ### WEB SERVER ###
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/jammy64"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.11"
  
    web01.vm.provider "virtualbox" do |vb|
      vb.name = "web01"
      vb.memory = "512"
    end
  end
  
  ### APPLICATION SERVER ###
  config.vm.define "app01" do |app01|
    app01.vm.box = "generic/rocky9"
    app01.vm.hostname = "app01"
    app01.vm.network "private_network", ip: "192.168.56.12"
  
    app01.vm.provider "virtualbox" do |vb|
      vb.name = "app01"
      vb.memory = "1024"
    end
  end
  
  ### MEMCACHE ###
  config.vm.define "mc01" do |mc01|
    mc01.vm.box = "generic/rocky9"
    mc01.vm.hostname = "mc01"
    mc01.vm.network "private_network", ip: "192.168.56.14"
  end
  
  ### DATABASE ###
  config.vm.define "db01" do |db01|
    db01.vm.box = "generic/rocky9"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.56.15"
  end
  
  ### RABBITMQ ###
  config.vm.define "rmq01" do |rmq01|
    rmq01.vm.box = "generic/rocky9"
    rmq01.vm.hostname = "rmq01"
    rmq01.vm.network "private_network", ip: "192.168.56.16"
  end
  
  end